    dist: trusty
    jdk: oraclejdk8
    language: java
    services:
      - postgresql
      - docker
    env:
      global:
        - secure: "M78Gbnw5QbqGUfBI/niHLk4zCcIXdiEKw9PJWAnv9sizdroZJb3ysaxlLKySljCtLUR6TbqH3qjYbwJ+WNNHzThQsWBQbwEApajWDu4Fx77CvYNdYMP+1lpSKdxsR3JFoTYh3FnLOMF9FEoAGWlFTSu8fOFhCWtYOItXo4qlHeMBzb1mERQQQdKMKcR16dj2ru49186OBfwBvd18Tstc1YtcMKIXVvonaHs6asRjF+dRQMW6+qXHcFqFoEHxi8FCC9WaQqbwrd7IS/kYY62eR3y5ms5ybWzR/1iByIxELNVoYQFPl/rn53iwflULWPlN9IkgKWCoGF6YIH94s7XxX/sLb4N+xd5T8Msm0APioedh1Ds2RY9cYwx4iyYMHfyGQ/ychazcO9yaRLsSTyc6bCD3DtOKgUfZa2m1WPdAAJ8qQ6ePJABKiQEChuahJiy+dr92LKWyPkyyaEDQQkIRjKGAs/vNaU3WKEJZHg0TPRf+9LhcHQG5DmD8kYtuB6Ae8zjZKojhoZkWwyggHKbUw0vXQGybUHO9rl2u9Wq30r3h/fP5A4Ih8pb7g3nnuFhGJsafaXh7W880uyjvojQZV8HfSeP95d/e/VlIsQqABlR5jMrOtjFijYo6gqnDgTTlHjuYQFsa66p2gD2pQzM3G427Cf4y+oqIwtdhN6SnLVU="
        - secure: "bPvEHrnlQattMDCDhsdxlIvsoGn/Q1v3caFuuicAVLKunkc9R/4YcntCEsYdHdDHkh2yriShsZcXi27euU8Hu7ckyH7JivVZSKjmmRQmABCTTHCKSRlvaVipiMKqI7jjuX1lg3PdLPwn8DxYbSSXatGUOmcQrNqRsLbpXCiG2flkOp+3csN/niFceWj04KUkFJMtUoW6402DuzHTX0CSi2uxTz0TfQVGeGSPEyXi/mxUar/na+D57XtrefpBYoo1e8Jjtsy7GeI6V4P+1o/lKZc08yb3mpf8hopu7POrjlDWE+KuBYgUmx9pcUXkSRv3uFc1fWGjtEm9PIkaUUwp53YfD6td1TitphOL0d8cgk9iLMiv+3mu+8IrAfPrgqrhWDQyi62i7W2oD3/3W++bXepDGeF+IIt3YDd0oym+xu8DQMUkz+j6mP1/jvxmi1+DvC9jN2gC9D0chnt/8iO3VLwku7a4ar+9Lx+q5/oTHhpzAboA5PT8bmgJCWdGCxdwzVFiiODI8WRj0WOj1dZnhODZCLmo6hphLnsLLR0wsycVezFoxeTYm6JdmYBnq6vEhwQ7fMOGJswuX91vrt69llykTsexWzAX3Z/4xvBMYTqT/v+Xubm1IPqdsqvhxaYiYgMfWSMSB9gClFSr4EAJEArwjC2bxXfjz+Z86vPoGqQ="
        - secure: "aN2WrBqC9hQ1SPZcQcz2EagnnxTLjXo0PlhjmGBoM4BSDolZWBBtB7Y9wwnNz8PfPaHxHdsMQPNxQ0ci1DHE05SJmUGBnkahI6wzyywnaix9R87wtYYeNviMvlTZVIyrZmxEyQqdke5EtC4YIqQ+Nj6kcftOKwxR/IAWAYRQPQWDPyVDs3Rsflv6GDHpzcxjw8K5gl8eFm788tWwapjjC1VvBfTVNZpXPvGqfe/i4om4eU7N9oLPepmoNb/75ZO0LiCDVCB8nDtUE0IedGxWfG54g/WDYWmzjqGOW3TTAFNR812EkM9dDgaz5rOZKYpBg3Bfq+CRClmrtB41KB356NdIb9KV5AfTR2wdghqRq7Baf2d8YLlvoriEdfbCQMbvnMicTXsriLzsIQKEFwjoI/oJjO2FJKvAP83oNetjl1AomVaLk7EsnRq9cG20I6/GDQyhPbqnuSQoYXwNiG/elNrB1eIF9s5kPl+TQcU6FeNZu/v/1Z6C8/SB++MvatEIous61GgppNpSHYrJMxPhFjwBN+Es5OVo78HvcPEI79Ke/5xvLUAMLd13nUZEnOGaApcyZhVgpT5lC3uyYYMluAe1abu88/4kg7b9cTSjPQ4KWDEy7Bd8SbV5R6PvAPJncoaJj6RXEV9f+VnktbcHxXQtc7/AQczrz9DmEyxde9U="
        - COMMIT=${TRAVIS_COMMIT::7}

    before_script:
      - psql -c "CREATE DATABASE myshopdb;" -U postgres
      - psql -c "CREATE USER root WITH PASSWORD 'root';" -U postgres

    script:
      - ./mvnw clean install -B

    after_success:
      - docker login -u $DOCKER_USER -p $DOCKER_PASS
      - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo "$TRAVIS_BRANCH"; fi`
      - export IMAGE_NAME=atygaev/heroku-shop-app
      - docker build -t $IMAGE_NAME:latest .
      - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
      - docker push $IMAGE_NAME:$TAG

    deploy:
      provider: heroku
      api_key: $HEROKU_API_KEY
      app: heroku-shop-app
