apiVersion: apps/v1
kind: Deployment
metadata:
  name: myspring
spec:
  replicas: 10
  selector:
    matchLabels:
      app: myspring
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: myspring
    spec:
      containers:
        - image: andreas111/myspring
          imagePullPolicy: Never
          name: myspring
          ports:
            - containerPort: 8080
      hostAliases:
        - ip: "192.168.49.2" # The IP of localhost from MiniKube
          hostnames:
          - postgres.local
